### PR TITLE
First milestone completed

### PR DESCRIPTION
**Pull request by sergiomauz**
- Added main.rb
- Created the executable file.
- Created directories LIB and BIN.
- Added "Hello World!" message.

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Good job :+1: 
You have all the required code for this milestone but we need to fix a few things before we can proceed to the next milestone.
- [ ] change `bin/main` to `bin/main.rb`
- [ ] The executable file `bin/main.rb` should display the same message as well as `ruby bin/main.rb`([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/execute_bin.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] submit for another review after the changes

### Martin Afani

**Comment by shshamim63** [comment]
## Status :ambulance: Changes Required :ambulance: 
___
Hi @sergiomauz and @peterrobert :wave: ,
Awesome job :clap: . You have covered all the changes asked by the previous reviewer but I can not see the most important task in this project. That is a linter configuration. And I am sorry that it was not mentioned in the previous review. Please follow the instructions below to complete this milestone.
___
### Mandatory Changes
___
1. Please follow the instructions mentioned in this [link](https://github.com/microverseinc/linters-config/tree/master/ruby) to set up a linter in this project.
___
#### Please resolve the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Twitter](https://twitter.com/Shshamim090)

**Comment by sergiomauz** [comment]
Added Rubocop.
Since the environment is set to ruby there is no reason for having a .rb extension on the file and hence we removed it.

**Review by suretrust — APPROVED** [review]
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future milestones and happy coding!_ 🎉

**Pull request merged**
