### PR TITLE
Second milestone

### PR DESCRIPTION
**Pull request by peterrobert**
1. Created the Game Board
2. Added the welcome message
3. Added player names
4.Added game reset

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Amazing
Your game structure looks good. You have handled most logic required for the game but you have not shown us how you would handle win/loss or draw situations. Please the logic for that.
- [x] [REQUIRED] game informs player if the selected move is a winning move
- [x]  [REQUIRED] game informs player if the selected move is a draw move
- [x] fix sticker errors and conflicts in the repo
- [x] change `bin/main` to `bin/main.rb`

### Martin Afani

**Comment by peterrobert** [comment]
1.fixed the linting errors
2.fixed conflicts with the development branch
3. The game now informs player if its winning move
4. The game informs player if it is a draw

**Comment by sergiomauz** [comment]
Done.

**Review by Forison — APPROVED** [review]
## Status:: Approved💚
# 🙋‍♂️ team,
Good job on implementing the changes requested in the previous review🙂. There is a dummy declaration after the eighth turn🙂.
# See you at the next milestone where🙂.
Happy coding💻
Addo Forison

**Pull request merged**
